### ISSUE TITLE
LaunchParams buffers are not updated sometimes

### ISSUE THREAD

**Issue by CoffeeExterminator** [DTolm/VkFFT#185]
Hi,
I was performing two forward ffts, using the same VkFFTApplication, but different output buffers, something like:
fft1:
```cpp
launchParams.inputBuffer = &inputHandle;
launchParams.buffer = &outputHandle1;
...
```
fft2:
```cpp
launchParams.inputBuffer = &inputHandle;
launchParams.buffer = &outputHandle2;
```
I have encountered a problem with ```VkFFTCheckUpdateBufferSet``` (vkFFT-UpdateBuffers.h). There are conditions upon which the buffers must be updated, such as:
```cpp
if ((launchParams->buffer != 0) && (app->configuration.buffer != launchParams->buffer))
```
Where ```buffer``` is a pointer to VkBuffer. In my case, through some coincidence, ```outputHandle2``` ended up at the same address as ```outputHandle1``` previously was, which resulted in whatever VkFFTCheckUpdateBufferSet is supposed to update not being updated, and the output for my second fft ended up in the ```outputHandle1``` buffer.
I have forcibly set ```performBufferSetUpdate = 1;``` before all the if's and that got it working correctly, but that's not the proper solution obviously and I would appreciate if you could do something about this.

**Comment by DTolm** [comment]
Hello,

This issue was closely related to your other issue. As VkFFT only stored the pointer to buffers, it was not possible to check each individual buffer if it was updated. Now that VkFFT stores all contents of the pointer, I have added a check that compares each individual buffer passed in launchParams to make a decision on the update.

Best regards,
Dmitrii

**Comment by CoffeeExterminator** [comment]
Hi,
This issue also seems fixed now, thank you.
