### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [DTolm/VkFFT#5]
Would you like to add more error handling for return values from functions like the following?
- [fread](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html "Binary input") ⇒ [VkFFTReadShader](https://github.com/DTolm/VkFFT/blob/68b707955953aa50d997a47233b2d9726466cc30/lib/vkFFT.h#L102)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/DTolm/VkFFT/blob/68b707955953aa50d997a47233b2d9726466cc30/Vulkan_FFT.cpp#L454)

**Comment by DTolm** [comment]
Sure, this absolutely has to be done in some way in the future when more people start using the code. There can be errors due to RAM/VRAM overflow that are unchecked at this moment. I just prioritized functionality first. If you have ideas on how this task should be managed, feel free to share your view.

Btw, Vulkan_FFT.cpp is not a part of the library, it is just an example on how the user can incorporate VkFFT in their own compute pipeline. User still has to manage their own buffers - this reduces total memory needed, as VkFFT doesn't allocate memory by itself.

**Comment by DTolm** [comment]
As I said, this is something that I need to dive into in the future. My mindset was features and performance first. If you know how to do this properly, I will happily accept a pr on this.

About the second point, sorry I was not clear. I am talking about big memory allocations, like a FFT system size buffers. All the allocations in vkFFT.h are really small and should not pose that big of a problem as a memory overflow. They are also accompanied with a free call. But sure, even this can break code for someone. The code is still in development, so I will try to  handle big problems first.

**Comment by elfring** [comment]
>… If you know how to do this properly, …

* I know some software development possibilities (for this issue).
* But I know also that corresponding views can be special by Vulkan developers according to affected components.

**Comment by DTolm** [comment]
Closed, as I have added error handling to most calls in the generator.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/DTolm/VkFFT/commit/2f2467df6e064c5fa7d197bb6aa5a983de6f0296 "Better error and issue handling").
