### ISSUE TITLE
VkFFTapp crash during cuda kernel preparation for specific sizes on Volta & Ampere cards (cuda bug?)

### ISSUE THREAD

**Issue by vincefn** [DTolm/VkFFT#59]
When preparing a VkFFTapp for a 1D C2C transforms, single precision, with sizes either 7623, 9009 or 10647, there is a segmentation fault (no other 1D radix size up to 100000 gives an issue).

This seems to be a CUDA bug, and not a VkFFT issue, but maybe you have some idea about that.

At first I encountered this using a V100 on a power9 machine (driver 418.126.02, cuda 10.1, nvcc V10.1.243) , but now I am also seeing this on an RTX 3080 Ti with a more recent driver 470.63.01 and cuda 11.4 (nvcc V11.4.48).

On another computer with a Titan V and a P6000, the same crash happens if the TitanV is used, but not the P6000. So this seems to happen on Volta and Ampere cards.

**Comment by DTolm** [comment]
Dear @vincefn,
No, this was a VkFFT issue for some sizes divisible by 9. It should be resolved now (fix only makes sure that the max number of registers is calculated correctly in such cases).
Best regards,
Dmitrii

**Comment by vincefn** [comment]
Thanks, it works now.

I did find another unrelated case in the meantime, with errors for some bluestein transforms (2D/3D DCT4 for N=171,181.. and 1D R2C with N in the 27xx range). That's with cuda for both a P6000 and a RTX 3080Ti.

See the results (ignore the errors, these are all timeouts or out of memory):
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/cuda-RTX3080Ti/pyvkfft-testcuRTX3080Ti.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/cuda/pyvkfft-test-cuda.html

Sorry about piling up all these reports, generally VkFFT is running great but I'd like to be thorough for the next release.

**Comment by vincefn** [comment]
Correction - in the 1D R2C case (double precision) with N in the 27xx range, this only happens on the RTX 3080Ti card, not the P6000 (both tested with the cuda backend)

**Comment by DTolm** [comment]
@vincefn,

I can confirm the issue with Bluestein's DCTs and it is fixed in the last update.

As for the 1D R2C, this is a more tricky one. I could only confirm it for the 2914 sequence on laptop 3070. It is somehow related to the synchronization of threads after Bluestein kernel multiplication in C2R, but the code shows that there is no communication between threads in the region that is causing issues. It might be somehow related to the compiler optimizations, as the same region in 2914 with a batch of 2 doesn't cause issues. Anyway, adding an explicit barrier apparently solves it for now.

I am really grateful for these reports, as they help to identify that there are only small mistakes and no architectural errors to fix.   Better to solve them sooner than later.

Best regards,
Dmitrii

**Comment by vincefn** [comment]
The ongoing test looks all good now on a p6000 with cuda:
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/cuda/pyvkfft-test.html
Testing is not finished but now it's mostly the same tests with different norm and lut options, so I don't expect failures.
(I also tested the RTX3080Ti just for the tests which failed, and they passed - I need to redo a full test to be sure)
